### ISSUE TITLE
[tradein] Krivi header

### ISSUE THREAD

**Issue by sasadj1** [wssto2/dacia-header-footer-2022#3]
Joža,
danas sam slučajno primjetio da je krivi h/f na stranici TradeIN Dacia, ali samo u Sloveniji: https://www.cenitev.dacia.si/
![image](https://user-images.githubusercontent.com/72204614/205866492-efb70a22-5a9e-4890-b8f3-4d7f11490dd3.png)

U Hr i Rs je ok!

Hvala,
pozdrav,
Sasa.

**Comment by jzlimen** [comment]
Riješeno
